# All employee details
get http://localhost:4004/odata/v4/company/Employees
###
# Single Employee Details
get http://localhost:4004/odata/v4/company/Employees/12

###
# Create an Employee
post http://localhost:4004/odata/v4/company/Employees
Content-Type: application/json

 {
      "Id": "7",
      "First_Name": "Udta",
      "Last_Name": "Punjab",
      "Phone_Number": "345678923",
      "Email":"abc@gmail.com",
      "Department": "KLT"
    }
###
# Get Departments List
get http://localhost:4004/odata/v4/company/Departments
###


# Create a Department   ----Not working the below api
post http://localhost:4004/odata/v4/company/Departments
Content-Type: application/json
 {
      "Id": "CAP",
      "Name": "Cloud Apllication Programing",
      "HOD": "Johny",
    }
